site_name: 'Documentation Programs Partners'
site_author: '@sortlist'
site_description: >-
  Affiliate Program

# Repository
# repo_name: 'sortlist/partners'
# repo_url: 'https://github.com/sortlist/infrastructure'

# Copyright
copyright: 'Copyright &copy; 2020 Sortlist'


nav:
  - Introduction: index.md
  # - Mise en route:
  #   - Demande effectuée: start/request_sent.md
  # - Call-to-actions:
  #   - Widget: cta/widget.md
  #   - Bannières: cta/banners.md
  #   - Lien: cta/link.md
  #   - Liste intégrée d'agences: cta/embed-agencies-list.md
  # - Création de contenu: content_creation.md


# Documentation and theme
theme:
  name: material
  favicon: sortlist-favicon.png
  logo: sortlist-logo-border-white.png

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: fr
  features:
    - tabs
  # palette:
  #   primary: blue
  #   accent: orange
  font:
    text: IBM Plex Sans
    code: SFMono-Regular,Consolas,Menlo,monospace

# Plugins
plugins:
  - search

extra_javascript:
  # - _assets/js/mermaid-8.5.0.min.js
extra_css:
  - stylesheets/extra.css

# Extras
# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: 'https://github.com/sortlist/infrastructure'



# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde